### PR TITLE
Collect constant resolution errors and fail. Closes #13.

### LINKED ISSUE #13: Collect invalid constants and fail
Currently invalid constants log a message at WARN level. This was done so that all invalid constants are detected at once. 
However they are really a fatal error, so they should instead be collected, and then Unpick should fail.

### PR DESCRIPTION
**Pull request by Daomephsta**
Upgrade constant resolution errors to SEVERE and throw RuntimeException if any occur.
Unfortunately the location means failure occurs after resolution of the first constant group with errors completes. I'm investigating doing better.

### CODE REVIEW

**Review by liach — APPROVED** [review]
Good idea. I recall we do have constant errors in current yarn, which I happened to discover when I was converting them to intermediary.

**Comment by liach** [comment]
Anyone mind check this out?

**Comment by Daomephsta** [comment]
The new commit is breaking due to the changes to `ConstantMappers`. However the only user of Unpick I am aware of is Loom, which interacts via the CLI. Unpick has not reached 1.0.0, and I don't see the use of avoiding breaking changes that aren't an issue for the sole user. I'm open to deprecating the old method instead though.

**Review by modmuss50 — APPROVED** [review]

**Comment by Daomephsta** [comment]
> Unpick has not reached 1.0.0, and I don't see the use of avoiding breaking changes that aren't an issue for the sole user. I'm open to deprecating the old method instead though.

Apparently Unpick is at v2.2.0, guess this goes into `dev/3.0`.

**Pull request merged**
